### ISSUE TITLE
Installation into IDE not using the $(BDSCommonDir) var - instead uses fixed CatalogRepository path into user folder

### ISSUE THREAD

**Issue by StatusPro-ziegelt** [MaxiDonkey/DelphiAnthropic#2]
Dear all,

when I use the GetIt Installer for your package, it uses my user folder CatalogRepository Folder instead of the global defined $(BDSCOMMONDIR).

Could this be fixed ?
![image](https://github.com/user-attachments/assets/9a91b67f-aac4-4f3b-9595-60831e0e6bee)

Thanks for your ideas !

**Comment by StatusPro-ziegelt** [comment]
Setting "@SET BDSCatalogRepository=" in rsvars.bat does the trick

**Comment by MaxiDonkey** [comment]
Thank you for bringing this to my attention and for finding a solution on your own. As you noted, the installation setup for GetIt packages, including the location of the CatalogRepository, is handled by Embarcadero and isn't within my control as the package provider. My role is to provide the package content, while Embarcadero configures its deployment in the IDE environment.

I'm glad to hear that setting @set BDSCatalogRepository= in rsvars.bat solved the issue for you. Please feel free to reach out if you have any other questions about the package itself.
